# Generated by Django 4.2 on 2025-06-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
