# Generated by Django 4.2 on 2025-06-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
