# Generated by Django 4.2 on 2025-06-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_alter_movie_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
